[package]
name = "rust-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"   # 可选：操作JS类型
web-sys = { version = "0.3", features = ["console"] } # 可选：访问Web API